### ISSUE TITLE
Failed to install with emacsPgtkGcc

### ISSUE THREAD

**Issue by pltanton** [vlaci/nix-doom-emacs#97] opened 2020-11-30 13:21 UTC
When trying to install doom-emacs using emacsPgtkGcc from https://github.com/nix-community/emacs-overlay I'v got an error.

```error: --- Error --- nix-daemon
builder for '/nix/store/w5818j6fw8xj9b7a80g4sgz8j25kqclz-straight-emacs-env.drv' failed with exit code 128; last 10 log lines:
  Compiling trampoline for handle-switch-frame
  Compiling trampoline for make-indirect-buffer
  Compiling trampoline for make-process
  Compiling trampoline for read-char
  Compiling trampoline for read-key-sequence
  Compiling trampoline for select-window
  Compiling trampoline for set-window-buffer
  Compiling trampoline for top-level
  Compiling trampoline for use-global-map
  Compiling trampoline for use-local-map
```

Full log:
```
❯ nix-store --read-log /nix/store/w5818j6fw8xj9b7a80g4sgz8j25kqclz-straight-emacs-env.drv
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Loading /nix/store/9n805fliic5nax2ja7s29f8vqrxdbw3p-emacs-gcc-20201129.0/share/emacs/site-lisp/site-start.el (source)...
Loading /nix/store/x0jskqihyfqwvqfryd615ilmdqr2vja6-doom-src/bin/doom...
Installing Doom Emacs!

> Creating /nix/store/mcbgm44m13ma3cx1gpp1z41cww17snnc-doom.d/
  ✓ Created /nix/store/mcbgm44m13ma3cx1gpp1z41cww17snnc-doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping
Generate an envvar file? (see `doom help env` for details)
[nix-doom-emacs] --> answering NO
Installing plugins
Compiling trampoline for abort-recursive-edit
Compiling trampoline for describe-buffer-bindings
Compiling trampoline for execute-kbd-macro
Compiling trampoline for handle-switch-frame
Compiling trampoline for make-indirect-buffer
Compiling trampoline for make-process
Compiling trampoline for read-char
Compiling trampoline for read-key-sequence
Compiling trampoline for select-window
Compiling trampoline for set-window-buffer
Compiling trampoline for top-level
Compiling trampoline for use-global-map
Compiling trampoline for use-local-map
```

I'm not sure, but for me it seems like doom install trying to restart itself with non 0 exit code? https://github.com/hlissner/doom-emacs/blob/e4890f6ac952272ba3136cd2d8b4321dd9dc9188/core/cli/packages.el#L265

Using doom install manually completes well.

UPD: Same with emacsGcc, or any other native compile emacs

**Comment by vlaci** [comment] 2020-11-30 21:49
Yeah, this recent change requires additional modification from my side.

**Comment by Mic92** [comment] 2021-08-03 09:24
Duplicate of https://github.com/vlaci/nix-doom-emacs/issues/115

**Closed** 2021-08-05 12:13 UTC
