### ISSUE TITLE
nix-doom-emacs no longer builds on darwin

### ISSUE THREAD

**Issue by starcraft66** [vlaci/nix-doom-emacs#263] opened 2021-07-02 15:23 UTC
When building my flake on my macbook with a recent version of `nix-doom-emacs`, I get:

```
error: The option `home-manager.users.tristan.services.emacs' does not exist. Definition values:
       - In `<unknown-file>':
           {
             _type = "if";
             condition = true;
             content = {
               package = <derivation /nix/store/krkhv33bgb8905lnbd5v44sca4mrncyb-emacs-with-packages-27.2.drv>;
           ...
(use '--show-trace' to show detailed location information)
```

I'm going to point some fingers and assume this is caused by https://github.com/vlaci/nix-doom-emacs/commit/71a2ea289967ca81708a1b4820c6e6a8361fca0a because home-manager's `services.emacs` is not defined on darwin.

Building two commits earlier works fine.

**Comment by vlaci** [comment] 2021-07-27 12:43
I am unfamiliar how nix-darwin woks. So the issue is that home-manager on Mac has no `services.emacs` option?

**Comment by babariviere** [comment] 2021-07-27 13:44
@vlaci the home-manager's `services.emacs` is only for Linux. On Darwin, it's a module defined by `nix-darwin`. Link to the doc: https://daiderd.com/nix-darwin/manual/index.html#opt-services.emacs.enable

**Comment by vlaci** [comment] 2021-07-27 15:04
I hope that it is now fixed. Feel free to reopen if it isn't

**Closed** 2021-07-27 15:04 UTC

**Comment by starcraft66** [comment] 2021-07-27 19:24
That fixed it, thanks.
