### ISSUE TITLE
syntax highlighting in org-mode code snippets not working

### ISSUE THREAD

**Issue by arjunv27** [vlaci/nix-doom-emacs#67] opened 2020-10-07 19:10 UTC
Hmm, just rebuilt my config without nix-doom-emacs and syntax highlighting in org-mode as usual. Was unable to discover issue with nix-doom-emacs. Using same doom.d configuration files for both.

**Comment by vlaci** [comment] 2020-10-08 06:53
It works fine for my personal configuration. Could you share your configuration where it doesn't work?

**Comment by vlaci** [comment] 2021-01-23 16:55
Closing as I was unable to reproduce the issue. Feel free to reopen if you still have this issue.

**Closed by vlaci** 2021-01-23 16:55 UTC
